# Generated by Django 4.1 on 2024-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0002_customer_order_product_stock_quantity_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
