# Generated by Django 4.1 on 2024-09-05 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0004_category_slug_alter_product_category_subcategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
    ]
