# Generated by Django 4.1 on 2024-09-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0005_rename_title_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="afriapp.category",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
