# Generated by Django 4.1 on 2024-09-06 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0007_alter_category_table_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
