# Generated by Django 5.1.1 on 2024-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0008_remove_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
